### ISSUE TITLE
Rethink data structures for transformed distributions

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#126]
When a transformation is linear, reconciliation leads to normal distributions and should be easy to implement provided we can identify that the transformation is linear.

``` r
library(fable)
#> Loading required package: fabletools

as_tsibble(cbind(mdeaths, fdeaths)) %>%
  aggregate_key(key, value = sum(value)) %>%
  model(ets = ETS(value+1)) %>%
  reconcile(ets = min_trace(ets)) %>% 
  forecast()
#> Warning: Reconciliation in fable is highly experimental. The interface will
#> likely be refined in the near future.
#> Reconciliation of non-normal forecasts is not yet supported.
```

<sup>Created on 2019-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
I think the right way to approach this would be to adjust how mathematical transformations on distributions work. Instead of testing if the transformation is linear for reconciliation, when a transformation is applied to a distribution it should 'evaluate' that transformation rather than changing the quantile method.

So much like `N(0,1)+1` gives `N(1,1)`, `{function(x) x + 1}(N(0,1))` should also give `N(1,1)` not `t(N(0,1))`. A bit more involved, `log(N(0,1) + 1)` should give `t(N(1,1))` not `t(N(0,1))`.

I'll support this when I re-implement distributions for `vctrs` support.

**Comment by mitchelloharawild** [comment]
Closing as sufficient discussion is now in {distributional}.
