### ISSUE TITLE
Error: Can't cast <lst_mdl> to <lst_mdl>.

### ISSUE THREAD

**Issue by realauggieheschmeyer** [tidyverts/fabletools#175]
Hello. I was hoping to get some help with the following error. No matter which model I try to fit (ARIMA, STL, etc.), I get an error message about casting `<lst_mdl>`. I couldn't find any other examples of someone running into this error and I'm not sure how to debug myself.

Any thoughts?

``` r
library(tsibble)
library(fable)
#> Loading required package: fabletools

tibble(date = seq.Date(as.Date('2019-01-01'), as.Date('2019-12-31'), 1),
       volume = arima.sim(n = 365, list(
         ar = c(0.8897,-0.4858),
         ma = c(-0.2279, 0.2488)
       ),
       sd = sqrt(0.1796))) %>% 
  as_tsibble(index = date) %>% 
  model(ARIMA(volume))
#> Error: Can't cast <lst_mdl> to <lst_mdl>.
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
This issue is being worked on right now :smile: 

The problem is due to changes in upcoming versions of tibble and dplyr. In the development version of these packages, they use vctrs to handle manipulation of data. The CRAN version of fable is incompatible with the development versions of tibble and dplyr. A dev version of fable(tools) that will resolve this issue will be available on GitHub today, and on CRAN next week.

**Comment by mitchelloharawild** [comment]
Added in dc1bd1c475dcad8fb4fff90ec93f3124674ed1f1
