### ISSUE TITLE
Distribution column named after target variable

### ISSUE THREAD

**Issue by markfairbanks** [tidyverts/fabletools#233]
When using `forecast()`, the resulting fable now names the distribution column after the target variable. Not sure if this is intended, it was called `.distribution` in the past:

``` r
library(fpp3)

tsibbledata::aus_production %>%
  model(ets = ETS(Beer)) %>%
  forecast(h = 1)
#> # A fable: 1 x 4 [1Q]
#> # Key:     .model [1]
#>   .model Quarter        Beer .mean
#>   <chr>    <qtr>      <dist> <dbl>
#> 1 ets    2010 Q3 N(405, 214)  405.
```

**Comment by mitchelloharawild** [comment]
This is an intentional change as the point forecast is now an optional component of the fable data structure. Previously there was no indication of if the point forecasts were forecast means, medians, or something else. Now these values can be computed directly from the distribution.
Please refer to the changelog for more details: https://fabletools.tidyverts.org/news/index.html#fabletools-020

**Comment by markfairbanks** [comment]
Ah gotcha. Good to know, thanks for the help

**Comment by tanner-ellison** [comment]
oops just seeing this, will close my recently opened ticket. sorry about that
