### ISSUE TITLE
Combining box_cox and centering/scaling

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverts/fabletools#252]
Is it possible to standardize the box_cox transformed output  by combining transformations somehow?  Also, how can you use automatic lambda selection for box_cox?

**Comment by mitchelloharawild** [comment]
Yes, transformations can be combined.

`box_cox(y - y_mu) ~ <model_specials>`

Automatic lambda selection like in the forecast package is not possible yet because it `box_cox(y, lambda = "auto")` is not invertible unless the automatically chosen `lambda` is stored somewhere. You can automatically choose `lambda` using the `feasts::guerrero()` feature.

``` r
library(feasts)
#> Loading required package: fabletools
as_tsibble(USAccDeaths) %>% 
  features(value, guerrero)
#> # A tibble: 1 x 1
#>   lambda_guerrero
#>             <dbl>
#> 1         -0.0398
```

<sup>Created on 2020-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
