### ISSUE TITLE
add measures of directional accuracy

### ISSUE THREAD

**Issue by davidtedfordholt** [tidyverts/fabletools#272]
I use MDA to characterize the likelihood of a model predicting the direction of change in trucking rates for a given lane with some frequency. I've got a PR to add MDA, MDV and MPDV measures of directional accuracy. 

The paper I reference calculates them slightly differently, in that it treats a period of no change as a positive change. Because I'm often comparing to a naive model, or using methods like Croston's where I often predict a 0 and often also see periods of precisely no change (especially in unit demand), I implemented it such that predicted changes of 0 are only considered accurate if the actual change was 0. I'm happy to change them so that they default to the original method, but I've run them on a number of cases and they don't meaningfully change the calculated directional accuracy of models unless they're in the specific case where the original method is problematic.

I was never sure of whether or not I should create a separate category of accuracy metrics. They deal with the point forecasts, but could be seen as a fundamentally different form of accuracy.

**Comment by mitchelloharawild** [comment]
I think a separate category of accuracy metrics is best - if only because `point_forecast_accuracy` is the default, and we probably have enough defaults for now. Sometime in the future, having a `default_forecast_accuracy` group would be nice, which may include measures of forecast distribution accuracy.

Long term, I also plan to better tag and describe accuracy measures in the same way features are for `feature_set()`.

This will allow you to tag the accuracy measures as "point" and "directional". Other tags may include "scale-dependent", "scale-independent", "interval", "distribution", etc.

**Comment by davidtedfordholt** [comment]
I'll get the category lined out then, before submitting the PR. (Plus, I need to make sure I've got the references straight)
